#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title A20 CPU temp
graph_vlabel cputemp
cputemp.label cputemp
graph_args --base 1000 -l 0
graph_category system
EOM
        exit 0;;
esac

printf "cputemp.value "
cat /sys/power/axp_pmu/pmu/temp
