#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Current consumed by A20
graph_vlabel current
current.label current
graph_args --base 1000 -l 0
graph_category system
current.warning 700000
current.critical 1000000
EOM
        exit 0;;
esac

printf "current.value "
cat /sys/power/axp_pmu/ac/amperage
