#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title ROS topics
graph_vlabel published topics
topics.label topics
graph_category ros
EOM
        exit 0;;
esac

printf "topics.value "
/opt/ros/kinetic/bin/rostopic list |wc -l
